// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter_google_map/consts.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FIREBASE_MAPS_API_KEY,
    appId: '1:131154865017:web:12dfb351859205fc169da8',
    messagingSenderId: '131154865017',
    projectId: 'solution-challenge-c7463',
    authDomain: 'solution-challenge-c7463.firebaseapp.com',
    storageBucket: 'solution-challenge-c7463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FIREBASE_MAPS_API_KEY,
    appId: '1:131154865017:android:f83acc1b6dc1f0ef169da8',
    messagingSenderId: '131154865017',
    projectId: 'solution-challenge-c7463',
    storageBucket: 'solution-challenge-c7463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FIREBASE_MAPS_API_KEY,
    appId: '1:131154865017:ios:5f7d57bb9959fc3f169da8',
    messagingSenderId: '131154865017',
    projectId: 'solution-challenge-c7463',
    storageBucket: 'solution-challenge-c7463.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FIREBASE_MAPS_API_KEY,
    appId: '1:131154865017:ios:501669caff050751169da8',
    messagingSenderId: '131154865017',
    projectId: 'solution-challenge-c7463',
    storageBucket: 'solution-challenge-c7463.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
